### ISSUE TITLE
Bot in Telegram don't work

### ISSUE THREAD

**Issue by COD3BREAK3R** [Edgar-P-yan/google-it-telegram-bot#15]
The bot in Telegram not work

**Comment by Edgar-P-yan** [comment]
Hi! I spent some time to redeploy it, and made sure that it'll work for at least couple of years on it's own :)
Check out the bot https://t.me/Google_itBot
And also the Telegram channel where i'll post news about Google_itBot and related projects: https://t.me/Google_itBot_feed.
Thanks!

**Comment by MaxL-hub** [comment]
The bot doesn't work again 😞
![EVlGZgY - Imgur](https://github.com/Edgar-P-yan/google-it-telegram-bot/assets/76598655/75b9c307-9d00-49c9-bed2-37ba23e57b17)

**Comment by Edgar-P-yan** [comment]
@MaxL-hub Hi! Thanks for pinging me, now it's working again.
I'll probably need to integrate a monitoring system to the bot
